version: "3.8"

services:
  hugo-dev:
    build:
      context: .
      dockerfile: Dockerfile.hugo-dev
    container_name: cloudmastery-docs
    ports:
      - "8888:8888" # Map container 8888 → host 8888
    volumes:
      - .:/src  # Mount current project to /src
    working_dir: /src
    restart: unless-stopped

  nginx-prod:
    build:
      context: .
      dockerfile: Dockerfile  # multi-stage Dockerfile that builds and copies to NGINX
    container_name: cloudmastery-nginx
    ports:
      - "80:80"
    restart: unless-stopped
