version: "3.8"

services:
  hugo:
    build: .
    container_name: cloudmastery-docs
    platform: linux/arm64 
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    command: hugo server --bind 0.0.0.0 -D --baseURL http://localhost:1313
    restart: always

  nginx:
    image: nginx:alpine
    container_name: cloudmastery-nginx
    depends_on:
      - hugo
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
