baseURL = "https://example.org/"
languageCode = "en-us"
title = "My Cloud Mastery Journey Site"
theme = "docsy"

[params]
  disableFontAwesome = false  # Set to false since Docsy requires it
  github_repo = "https://github.com/Priya-coding/CloudMasteryBlueprints"
  description = "A Documentation Site for Cloud Mastery"
